# aur-repo-filter
# Autogenerated from man page /usr/share/man/man1/aur-repo-filter.1.gz
complete -c aur-repo-filter -s a -l all -l sync -d 'Query all available pacman repositories. RB ( "pacsift " --sync ) '
complete -c aur-repo-filter -s d -l database -d 'Restrict output to the pacman repository R NAME '
complete -c aur-repo-filter -l sysroot -d 'Set an alternate system root.  See  pacutils-sysroot (7)'
complete -c aur-repo-filter -l config -d 'Set an alternate pacman. conf (5) file path'

