# aur-chroot
# Autogenerated from man page /usr/share/man/man1/aur-chroot.1.gz
complete -c aur-chroot -s D -l directory -d 'The base directory for containers'
complete -c aur-chroot -s C -l pacman-conf -d 'The  pacman. conf (5) file used inside the container'
complete -c aur-chroot -s M -l makepkg-conf -d 'The  makepkg. conf (5) file used inside the container'
complete -c aur-chroot -l cargs -l makechrootpkg-args -d 'Arguments (comma-separated) to be passed to  makechrootpkg for   --build '
complete -c aur-chroot -l margs -l makepkg-args -d 'Additional (comma-separated)  makepkg  arguments for  makechrootpkg '
complete -c aur-chroot -l bind -d 'Bind a directory read-only to the container. RB ( makechrootpkg " " -D ) '
complete -c aur-chroot -l bind-rw -d 'Bind a directory read-write to the container. RB ( makechrootpkg " " -d ) '
complete -c aur-chroot -l checkpkg -d 'Run  checkpkg (1) on the built package'
complete -c aur-chroot -s N -l namcap -d 'Run  namcap (1) on the built package'
complete -c aur-chroot -s T -l temp -d 'Build in a temporary container'
complete -c aur-chroot -s B -l build -d 'Build a package inside the container with makechrootpkg .  Assumes'
complete -c aur-chroot -l create -d 'was run at least once'
complete -c aur-chroot -s U -l update -d 'Update or create the /root copy of the container with arch-nspawn '
complete -c aur-chroot -l path -d 'Print the path to the container template ( $directory/root )'
complete -c aur-chroot -l suffix -d 'option.  The component <machine> is taken from uname -m '
complete -c aur-chroot -l user -d 'Run the host makepkg (8) instance as the specified user.  (makechrootpkg -U)'
complete -c aur-chroot -s d -d respectively

