# aur-pkglist
# Autogenerated from man page /usr/share/man/man1/aur-pkglist.1.gz
complete -c aur-pkglist -s b -l pkgbase -d 'Retrieve  pkgbases. git/pkgbase. json '
complete -c aur-pkglist -s n -l pkgname -d 'Retrieve  pkgnames. git/pkgname. json .  This is the default'
complete -c aur-pkglist -l users -d 'Retrieve  users. git/users. json '
complete -c aur-pkglist -s i -l info -d 'Retrieve  metadata. git/pkgname. json '
complete -c aur-pkglist -l plain -d 'Print the package list to standard output'
complete -c aur-pkglist -s F -l fixed-strings -d 'Interpret the given  pattern as a list of fixed strings, separated by newline…'
complete -c aur-pkglist -s P -l perl-regexp -d 'Interpret the given  pattern as a Perl-compatible regular expression (PCRE)'
complete -c aur-pkglist -s q -s u -l quiet -d 'Update the package list and print its path to standard output'
complete -c aur-pkglist -s Q -l systime -d 'Use the system clock when verifying the list modification date (see  --time )'
complete -c aur-pkglist -s t -l ttl -d 'A positive integer specifying the delay in seconds for retrieving list upgrad…'
complete -c aur-pkglist -l time -d 'This option should only be used when the clock is synchronized, for example w…'
complete -c aur-pkglist -s v -l verify -d 'Verify checksums of the compressed list with sha256sum (1)'

