# aur-query
# Autogenerated from man page /usr/share/man/man1/aur-query.1.gz
complete -c aur-query -s b -l by -d 'Arguments for package search . RB ( --type=search )'
complete -c aur-query -s t -l type -d 'Type of request.  Can be one of search , info , or suggest '
complete -c aur-query -s A -o fgLsSq

