# aur-format
# Autogenerated from man page /usr/share/man/man1/aur-format.1.gz
complete -c aur-format -s f -l format -d 'The character  % is followed by one of the following flags, corresponding to …'
complete -c aur-format -s d -l delim -d 'The delimiter for expanding arrays.  Defaults to a single space'
complete -c aur-format -l gron -d 'Format output similar to  gron (1)'
complete -c aur-format -s v -l verbose -d 'If a field is empty, replace it with a hyphen'

