# darktable
# Autogenerated from man page /usr/share/man/man1/darktable.1.gz
complete -c darktable -l cachedir -d 'X Item "--cachedir <cache directory>" darktable keeps a cache of image thumbn…'
complete -c darktable -l conf -d 'X Item "--conf <key>=<value>" darktable supports a rich set of configuration …'
complete -c darktable -l configdir -d 'X Item "--configdir <config directory>" This option defines the directory whe…'
complete -c darktable -s d -d 'X Item "-d <debug option>" This option enables debug output to the terminal'
complete -c darktable -l datadir -d 'X Item "--datadir <data directory>" This option defines the directory where d…'
complete -c darktable -l disable-opencl -d 'X Item "--disable-opencl" Prevent darktable from initializing the OpenCL subs…'
complete -c darktable -s h -l help -d 'X Item "-h, --help" Show the available command line options and exit'
complete -c darktable -l library -d 'X Item "--library <library file>" darktable keeps image information in an sql…'
complete -c darktable -l localedir -d 'X Item "--localedir <locale directory>" The place where darktable finds its l…'
complete -c darktable -l luacmd -d 'X Item "--luacmd <lua command>" A string containing lua commands to execute a…'
complete -c darktable -l moduledir -d 'X Item "--moduledir <module directory>" darktable has a modular structure and…'
complete -c darktable -l noiseprofiles -d 'X Item "--noiseprofiles <noiseprofiles json file>" darktable\'s profiled denoi…'
complete -c darktable -s t -d 'X Item "-t <num openmp threads>" darktable uses OpenMP to parallelize many co…'
complete -c darktable -l tmpdir -d 'X Item "--tmpdir <tmp directory>" The place where darktable stores its tempor…'
complete -c darktable -l version

