# darktable-cli
# Autogenerated from man page /usr/share/man/man1/darktable-cli.1.gz
complete -c darktable-cli -l width -d 'X Item "--width <max width>" This optional parameter allows one to limit the …'
complete -c darktable-cli -l height -d 'X Item "--height <max height>" This optional parameter allows one to limit th…'
complete -c darktable-cli -l bpp -d 'X Item "--bpp <bpp>" An optional parameter to define the bit depth of the exp…'
complete -c darktable-cli -l hq -d 'X Item "--hq <0|1|true|false>" A flag that defines whether to use high qualit…'
complete -c darktable-cli -l upscale -d 'X Item "--upscale <0|1|true|false>" A flag that defines whether to allow upsc…'
complete -c darktable-cli -l export_masks -d 'X Item "--export_masks <0|1|true|false>" A flag that defines whether masks us…'
complete -c darktable-cli -l style -d 'X Item "--style <style name>" Specify the name of a style to be applied durin…'
complete -c darktable-cli -l style-overwrite -d 'X Item "--style-overwrite" The specified style overwrites the history stack i…'
complete -c darktable-cli -l apply-custom-presets -d 'X Item "--apply-custom-presets" With this option you can decide if darktable …'
complete -c darktable-cli -l verbose -d 'X Item "--verbose" Enables verbose output'
complete -c darktable-cli -l core

