# dselect
# Autogenerated from man page /usr/share/man/man1/dselect.1.gz
complete -c dselect -l admindir -d 'X Item "--admindir directory" Changes the directory where the dpkg \'status\', …'
complete -c dselect -l instdir -d 'X Item "--instdir directory" Set the installation directory, which refers to …'
complete -c dselect -l root -d 'X Item "--root directory" Set the root directory to directory, which sets the…'
complete -c dselect -o Dfile -l debug -d 'X Item "-Dfile, --debug file" Turn on debugging'
complete -c dselect -l expert -d 'X Item "--expert" Turns on expert mode, i. e'
complete -c dselect -l color -d 'X Item "--color screenpart:[foreground],[background][:attr[+attr]. ]"'
complete -c dselect -l colour -d 'X Item "--colour screenpart:[foreground],[background][:attr[+attr]. ]" '
complete -c dselect -s '?' -l help -d 'X Item "-?, --help" Print a brief help text and exit successfully'
complete -c dselect -l version

