# flickrdf
# Autogenerated from man page /usr/share/man/man1/flickrdf.1.gz
complete -c flickrdf -s h -l help -d 'Show summary of options and exit'
complete -c flickrdf -s v -l version -d 'Display the version of the program and exit'
complete -c flickrdf -s d -l delay -d 'Set delay between requests to DELAY milliseconds'
complete -c flickrdf -s D -l debug -d 'Print lots of debugging output'
complete -c flickrdf -s o -l output -d 'Set output format to FORMAT'

