# flickcurl-config
# Autogenerated from man page /usr/share/man/man1/flickcurl-config.1.gz
complete -c flickcurl-config -l prefix -d 'Get the flickcurl installation prefix'
complete -c flickcurl-config -l libs -d 'Print library linking information'
complete -c flickcurl-config -l private-libs -d 'Print library private/static linking information'
complete -c flickcurl-config -l cflags -d 'Print pre-processor and compiler flags'
complete -c flickcurl-config -l help -d 'display this help and exit'
complete -c flickcurl-config -l version -d 'output version information'
complete -c flickcurl-config -l version-decimal -d 'Output version as a decimal integer'

