# jcmd-openjdk23
# Autogenerated from man page /usr/share/man/man1/jcmd-openjdk23.1.gz
complete -c jcmd-openjdk23 -o all -d Compiler
complete -c jcmd-openjdk23 -s H -d '[bu] 2'
complete -c jcmd-openjdk23 -s s -d 'Compiler. perfmap [arguments] (Linux only) Write map file for Linux perf tool'
complete -c jcmd-openjdk23 -o parallel -d 'heap inspection'
complete -c jcmd-openjdk23 -o gz -d 'gzipped format using the given compression level'
complete -c jcmd-openjdk23 -o overwrite -d 'overwritten if it exists (BOOLEAN, false) [bu] 2'
complete -c jcmd-openjdk23 -s F -d '[dq]vm_memory_map_. txt[dq]) System'
complete -c jcmd-openjdk23 -o format -d '[dq]json[dq]) (STRING, plain)'
complete -c jcmd-openjdk23 -s e -d 'false) [bu] 2'
complete -c jcmd-openjdk23 -s l -d '(BOOLEAN, false) VM'
complete -c jcmd-openjdk23 -s i -d '(BOOLEAN, false) [bu] 2'
complete -c jcmd-openjdk23 -o verbose -d class
complete -c jcmd-openjdk23 -o date -d '(BOOLEAN, false) VM. version Print JVM version information.  Impact: Low'

