# jinfo-openjdk23
# Autogenerated from man page /usr/share/man/man1/jinfo-openjdk23.1.gz
complete -c jinfo-openjdk23 -o flag -d 'Prints the name and value of the specified command-line flag'
complete -c jinfo-openjdk23 -o ']name' -d 'Enables or disables the specified Boolean command-line flag'
complete -c jinfo-openjdk23 -o flags -d 'Prints command-line flags passed to the JVM'
complete -c jinfo-openjdk23 -o sysprops -d 'Prints Java system properties as name-value pairs'
complete -c jinfo-openjdk23 -s h -o help -d 'Prints a help message'

