# jstack-openjdk23
# Autogenerated from man page /usr/share/man/man1/jstack-openjdk23.1.gz
complete -c jstack-openjdk23 -s l -d 'The long listing option prints additional information about locks'
complete -c jstack-openjdk23 -s h -o help -d 'Prints a help message'

