# timeshift-gtk
# Autogenerated from man page /usr/share/man/man1/timeshift-gtk.1.gz
complete -c timeshift-gtk -l debug -d 'Print debug information'
complete -c timeshift-gtk -l h -d 'Show all options'
complete -c timeshift-gtk -l version -d 'Print version number'

