#!/bin/bash
if [ "$(which semanage 2> /dev/null)" != '' ];then
  semanage fcontext -d -t cupsd_rw_etc_t '/opt/brother/fax/brmfcfax/inf(/.*)?'
  semanage fcontext -d -t cupsd_rw_etc_t '/opt/brother/fax/brmfcfax/lists(/.*)?'
  semanage fcontext -d -t bin_t          '/opt/brother/fax/brmfcfax/lpd(/.*)?'
  semanage fcontext -d -t bin_t          '/opt/brother/fax/brmfcfax/cupswrapper(/.*)?'

  if [ "$(which restorecon  2> /dev/null)" != '' ];then
    restorecon -R /opt/brother
  fi
fi
exit 0