# aur-depends
# Autogenerated from man page /usr/share/man/man1/aur-depends.1.gz
complete -c aur-depends -s a -l all -l show-all -d 'Include direct  pacman (8) dependencies of dependencies in the output'
complete -c aur-depends -s n -l pkgname -d 'Print dependency information to stdout as  pkgname instead of  pkgbase '
complete -c aur-depends -s t -l table -d 'Print dependency information in the following format:'
complete -c aur-depends -s r -l reverse -d 'Print  \\%dependstpkgbase pairs as input for  tsort (1)'
complete -c aur-depends -s J -l json -d 'Print dependency information as JSON'
complete -c aur-depends -l jsonl -d 'Print dependency information as JSON Lines (newline delimited JSON)'
complete -c aur-depends -l optdepends -d option
complete -c aur-depends -l no-depends
complete -c aur-depends -l no-makedepends -d and
complete -c aur-depends -l no-checkdepends -d options
complete -c aur-depends -l no-provides -d option
complete -c aur-depends -l assume-installed -d 'option.  Multiple packages can be specified by separating them with a comma'
complete -c aur-depends -l verify -d 'option is specified'

