# aur-vercmp
# Autogenerated from man page /usr/share/man/man1/aur-vercmp.1.gz
complete -c aur-vercmp -s a -l all -d 'Show packages with an older or equal version in the AUR'
complete -c aur-vercmp -s c -l current -d 'Changes format to print packages with an equal or newer version to  stdout '
complete -c aur-vercmp -s p -l path -d 'Read package versions from FILE instead of the AUR'
complete -c aur-vercmp -s q -l quiet -d 'Only print package names to standard output'
complete -c aur-vercmp -s u -l upair -d 'Print unpairable lines from file FILENUM, where FILENUM is 1 or 2 (join -a)'

