# aur-fetch
# Autogenerated from man page /usr/share/man/man1/aur-fetch.1.gz
complete -c aur-fetch -l sync -l merge -d 'Run  git-fetch (1) and merge upstream changes with  git-merge (1)'
complete -c aur-fetch -l rebase -d 'Run  git-rebase (1) instead of  git-merge (1), re-applying local commits on t…'
complete -c aur-fetch -l auto -d 'Run  git-rebase (1) for a repository with  aurutils'
complete -c aur-fetch -l reset -d 'Retrieve new revisions with  git-fetch origin and  git-reset to the  master@{…'
complete -c aur-fetch -l discard -d 'When using  --sync=merge or  --sync=rebase , uncommitted changes may cause th…'
complete -c aur-fetch -l existing -d 'Check if a git repositories exist in AUR using  git-ls-remote (1) before retr…'
complete -c aur-fetch -s r -l recurse -d 'Download packages and their dependencies with  aur-depends (1)'
complete -c aur-fetch -l results -d 'Write colon-delimited output in the following form to R FILE :'
complete -c aur-fetch -l ff
complete -c aur-fetch -l ff-only
complete -c aur-fetch -l no-commit -d and
complete -c aur-fetch -l no-ff -d 'options to git-merge .  Note: When previewing changes with'

