# aur-search
# Autogenerated from man page /usr/share/man/man1/aur-search.1.gz
complete -c aur-search -s a -l any -d 'Show the union of results instead of the intersection'
complete -c aur-search -s s -l search -d 'Use the  searchby interface.  This is the default'
complete -c aur-search -s i -l info -d 'Use the  info interface'
complete -c aur-search -s q -l short -d 'Only display package name, version and description'
complete -c aur-search -s r -l json -l raw -d 'Display results as JSON'
complete -c aur-search -l format-stdin -d 'Format JSON from standard input, assumed to match  aur-format (1) output'
complete -c aur-search -s v -l verbose -d 'Display more package information'
complete -c aur-search -s k -l key -d 'Sort results via a key, defaulting to R Name '
complete -c aur-search -s d -l desc -d 'Search by package name and description'
complete -c aur-search -s m -l maintainer -d 'Search by package maintainer'
complete -c aur-search -l submitter -d 'Search by package submitter'
complete -c aur-search -s n -l name -d 'Search by package name'
complete -c aur-search -l depends -l makedepends -l optdepends -l checkdepends -l provides -l conflicts -l replaces -l groups -l comaintainers -d 'Search for packages with keywords in depends , makedepends , optdepends , che…'

