# aur-srcver
# Autogenerated from man page /usr/share/man/man1/aur-srcver.1.gz
complete -c aur-srcver -s a -l arg-file -d 'Read source directories from  FILE instead of the command-line'
complete -c aur-srcver -l buildscript -d 'Read the package script  NAME instead of the  PKGBUILD default'
complete -c aur-srcver -l noprepare -l no-prepare -d 'Do not run the prepare() function in the PKGBUILD'
complete -c aur-srcver -s j -l jobs -d 'Set the amount of  makepkg processes run in parallel'
complete -c aur-srcver -l margs -l makepkg-args -d 'Additional arguments to pass to  makepkg (8)'
complete -c aur-srcver -l null -d 'When reading arguments with'
complete -c aur-srcver -l nobuild
complete -c aur-srcver -l nodeps -d and
complete -c aur-srcver -l skipinteg

