# aur-view
# Autogenerated from man page /usr/share/man/man1/aur-view.1.gz
complete -c aur-view -l format -d 'If  TYPE is  diff or  log , generate diffs with  git-diff (1) or  git-log (1)…'
complete -c aur-view -l exclude -d 'Do not include  FILE in the  git-diff (1) or  git-log (1) output'
complete -c aur-view -l no-patch -d 'Suppress patch output, only showing a summary'
complete -c aur-view -l revision -d 'The revision used for comparing changes.  Defaults to R HEAD '
complete -c aur-view -l prefix -d 'Prepend paths from command-line arguments or  --arg-file to  git-diff (1) and…'
complete -c aur-view -s a -l arg-file -d 'A textfile describing git repositories relative to the current directory'
complete -c aur-view -l confirm -d 'Display a confirmation prompt after the file manager has exited successfully'

