# darktable-generate-cache
# Autogenerated from man page /usr/share/man/man1/darktable-generate-cache.1.gz
complete -c darktable-generate-cache -s h -l help -d 'X Item "-h, --help" Gives usage information and terminates'
complete -c darktable-generate-cache -l version -d 'X Item "--version" Gives copyright and version information and terminates'
complete -c darktable-generate-cache -l min-mip -d 'X Item "--min-mip <0-7>"'
complete -c darktable-generate-cache -s m -l max-mip -d 'X Item "-m, --max-mip <0-7>" '
complete -c darktable-generate-cache -l min-imgid -d 'X Item "--min-imgid <N>"'
complete -c darktable-generate-cache -l max-imgid -d 'X Item "--max-imgid <N>" '
complete -c darktable-generate-cache -l core

