# rmiregistry-openjdk23
# Autogenerated from man page /usr/share/man/man1/rmiregistry-openjdk23.1.gz
complete -c rmiregistry-openjdk23 -o Joption -d 'Used with any Java option to pass the option following the'
complete -c rmiregistry-openjdk23 -s J -s J -d 'Java interpreter'

