# simple-mtpfs
# Autogenerated from man page /usr/share/man/man1/simple-mtpfs.1.gz
complete -c simple-mtpfs -s o -d 'mount options'
complete -c simple-mtpfs -s h -l help -d 'print help'
complete -c simple-mtpfs -s V -l version -d 'print version . SS "SIMPLE-MTPFS options:"'
complete -c simple-mtpfs -s l -l list-devices -d 'list available MTP devices.  Supports <device> option'
complete -c simple-mtpfs -l device -d 'select device no.  to mount'
complete -c simple-mtpfs -s d -d 'enable debug output (implies -f)'
complete -c simple-mtpfs -s f -d 'foreground operation'
complete -c simple-mtpfs -s s -d 'disable multi-threaded operation'

