// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1742636842);
user_pref("app.update.lastUpdateTime.background-update-timer", 1742636842);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1742670498);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1742636842);
user_pref("basebrowser.migration.version", 3);
user_pref("browser.aboutConfig.showWarning", false);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.migration.version", 148);
user_pref("browser.new_identity.confirm_newnym", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\",\"canvasblocker_kkapsner_de\"],\"idsInUrlbar\":[\"canvasblocker_kkapsner_de\",\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.security_level.noscript_inited", true);
user_pref("browser.security_level.security_custom", false);
user_pref("browser.security_level.security_slider", 4);
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage", "chrome://browser/content/blanktab.html");
user_pref("browser.startup.homepage_override.buildID", "20250303093702");
user_pref("browser.startup.homepage_override.mstone", "128.8.0");
user_pref("browser.startup.homepage_override.mullvadbrowser.version", "14.0.7");
user_pref("browser.startup.lastColdStartupCheck", 1742669866);
user_pref("browser.toolbars.bookmarks.showOtherBookmarks", false);
user_pref("browser.toolbars.bookmarks.visibility", "always");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[\"_contain-facebook-browser-action\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"bookmarks-menu-button\",\"urlbar-container\",\"downloads-button\",\"_73a6fe31-595d-460b-a920-fcc0f8843232_-browser-action\",\"fxa-toolbar-menu-button\",\"ublock0_raymondhill_net-browser-action\",\"cookieautodelete_kennydo_com-browser-action\",\"_3579f63b-d8ee-424f-bbb6-6d0ce3285e6a_-browser-action\",\"unified-extensions-button\",\"canvasblocker_kkapsner_de-browser-action\",\"jid1-mnnxcxisbpnsxq_jetpack-browser-action\",\"_ddc62400-f22d-4dd3-8b4a-05837de53c2e_-browser-action\",\"_9aa46f4f-4dc7-4c06-97af-5035170634fe_-browser-action\",\"_d19a89b9-76c1-4a61-bcd4-49e8de916403_-browser-action\",\"new-identity-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"_d19a89b9-76c1-4a61-bcd4-49e8de916403_-browser-action\",\"ublock0_raymondhill_net-browser-action\",\"_73a6fe31-595d-460b-a920-fcc0f8843232_-browser-action\",\"developer-button\",\"canvasblocker_kkapsner_de-browser-action\",\"_3579f63b-d8ee-424f-bbb6-6d0ce3285e6a_-browser-action\",\"cookieautodelete_kennydo_com-browser-action\",\"_contain-facebook-browser-action\",\"jid1-mnnxcxisbpnsxq_jetpack-browser-action\",\"_9aa46f4f-4dc7-4c06-97af-5035170634fe_-browser-action\",\"_ddc62400-f22d-4dd3-8b4a-05837de53c2e_-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"unified-extensions-area\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":20,\"currentVersionBaseBrowser\":2,\"currentVersionMullvadBrowser\":1,\"newElementCount\":3}");
user_pref("browser.urlbar.placeholderName.private", "Mullvad Leta");
user_pref("browser.warnOnQuitShortcut", false);
user_pref("distribution.archlinux-aur.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "128.8.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "US");
user_pref("dom.security.https_only_mode_ever_enabled", true);
user_pref("dom.security.https_only_mode_ever_enabled_pbm", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 36);
user_pref("extensions.hideNoScript", false);
user_pref("extensions.installedDistroAddon.uBlock0@raymondhill.net", true);
user_pref("extensions.installedDistroAddon.{73a6fe31-595d-460b-a920-fcc0f8843232}", true);
user_pref("extensions.installedDistroAddon.{d19a89b9-76c1-4a61-bcd4-49e8de916403}", true);
user_pref("extensions.lastAppBuildId", "20250303093702");
user_pref("extensions.lastAppVersion", "128.8.0");
user_pref("extensions.lastMullvadBrowserVersion", "14.0.7");
user_pref("extensions.lastPlatformVersion", "128.8.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.extension.hidden", false);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.ui.sitepermission.hidden", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.@contain-facebook", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.CanvasBlocker@kkapsner.de", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.CookieAutoDelete@kennydo.com", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.jid1-MnnxcxisBPnSXQ@jetpack", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.{3579f63b-d8ee-424f-bbb6-6d0ce3285e6a}", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.{73a6fe31-595d-460b-a920-fcc0f8843232}", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.{9AA46F4F-4DC7-4c06-97AF-5035170634FE}", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.{d19a89b9-76c1-4a61-bcd4-49e8de916403}", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.{ddc62400-f22d-4dd3-8b4a-05837de53c2e}", true);
user_pref("extensions.webextensions.uuids", "{\"{73a6fe31-595d-460b-a920-fcc0f8843232}\":\"2f5299a0-c93a-4c12-8867-db1f20f1b27c\",\"{d19a89b9-76c1-4a61-bcd4-49e8de916403}\":\"ce45f97f-ce35-4c07-9ee6-1c6aeb87ea74\",\"uBlock0@raymondhill.net\":\"3fef59a8-6b3d-4e34-a468-cf6dc3517c30\",\"default-theme@mozilla.org\":\"c5ce027c-679c-4fa9-b3ef-ab5e36569a87\",\"CanvasBlocker@kkapsner.de\":\"38bf84de-0328-432f-aa29-8e959a89088e\",\"{3579f63b-d8ee-424f-bbb6-6d0ce3285e6a}\":\"2de72673-c7d0-45f3-a81c-fe79e9f4fb40\",\"CookieAutoDelete@kennydo.com\":\"22da2cca-3dd0-4dbb-9119-1b4d2e9c769e\",\"@contain-facebook\":\"c9cb9209-ed4c-4669-a823-77b695e43fdd\",\"jid1-MnnxcxisBPnSXQ@jetpack\":\"6814ec42-8595-4ed0-8658-d3fa53ce2261\",\"{9AA46F4F-4DC7-4c06-97AF-5035170634FE}\":\"b83a52d7-4696-4829-ac39-43a2abc62ab9\",\"{ddc62400-f22d-4dd3-8b4a-05837de53c2e}\":\"b877783c-b587-4ac2-a504-7a5d146989db\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("gfx.blacklist.dmabuf.failureid", "FEATURE_FAILURE_DL_BLOCKLIST_NO_ID");
user_pref("idle.lastDailyNotification", 1742657295);
user_pref("intl.accept_languages", "en-US, en");
user_pref("intl.language_notification.shown", true);
user_pref("media.gmp-manager.buildID", "20250303093702");
user_pref("media.gmp-manager.lastCheck", 1742656147);
user_pref("media.gmp-manager.lastEmptyCheck", 1742656147);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.videocontrols.picture-in-picture.video-toggle.enabled", false);
user_pref("media.videocontrols.picture-in-picture.video-toggle.first-seen-secs", 1742656589);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("permissions.default.camera", 2);
user_pref("permissions.default.desktop-notification", 2);
user_pref("permissions.default.geo", 2);
user_pref("permissions.default.microphone", 2);
user_pref("permissions.default.xr", 2);
user_pref("places.database.lastMaintenance", 1742657295);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.globalprivacycontrol.was_ever_enabled", true);
user_pref("privacy.history.custom", true);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.resistFingerprinting.letterboxing.didForceSize", true);
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs2", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.userContext.enabled", true);
user_pref("privacy.userContext.extension", "@contain-facebook");
user_pref("privacy.userContext.ui.enabled", true);
user_pref("security.sandbox.content.tempDirSuffix", "3820a1d4-a772-45a1-8899-4d1b1e28d355");
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1742657295);
user_pref("toolkit.startup.last_success", 1742669864);
user_pref("toolkit.telemetry.cachedClientID", "9cc59c47-be0f-4d7d-a016-94caa5b3ae97");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
